# Generated by Django 3.2.16 on 2024-05-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(blank=True, default='../../media/users/user_default_profile.png', null=True, upload_to='../../media/users/pictures/', verbose_name='Picture'),
        ),
    ]
